"""EN: Shared layout constants for auth screens.
RU: Общие константы раскладки для экранов аутентификации.
"""

DIVIDER_W = 1

ZONE_PADDING = 24
ZONE_SPACING = 12
ZONE_LEFT_RATIO = 0.8
ZONE_RIGHT_RATIO = 0.2
FORGOT_BTN_W = 220
TITLE_FALLBACK_SIZE = 24
BTN_WIDTH_RATIO = 2.0

FIELD_H = 48
BTN_H = 48

TITLE_STYLE = "H4"
START_BTN_W_RATIO = 0.5

# Rating dialog layout tuning (shared settings)
RATING_DIALOG_WIDTH_RATIO = 0.86
RATING_DIALOG_HEIGHT_RATIO = 0.70
RATING_TABLE_HEADER_HEIGHT_RATIO = 0.08
RATING_TABLE_ROW_HEIGHT_RATIO = 0.075
RATING_OK_ROW_HEIGHT_RATIO = 0.14
RATING_OK_BUTTON_WIDTH_RATIO = 0.8
RATING_OK_BUTTON_HEIGHT_RATIO = 0.65
RATING_GRID_LINE_WIDTH = 1.2
